export const WIDTH = 400;
export const HEIGHT = 150;
export const ASPECT_RATIO = WIDTH / HEIGHT;
export const OPEN_WIDTH = WIDTH;
export const OPEN_HEIGHT = HEIGHT * 4;
export const DETAILS_WIDTH = 1024 - 250;
export const DETAILS_HEIGHT = Math.round(1024 / 1.5);
export const DETAILS_ASPECT_RATIO = DETAILS_WIDTH / DETAILS_HEIGHT;

export const WORLD_WIDTH = 0.2;
export const WORLD_HEIGHT = WORLD_WIDTH / ASPECT_RATIO;
export const WORLD_DEPTH = 0.01;

export const WORLD_OPEN_WIDTH = WORLD_WIDTH;
export const WORLD_OPEN_HEIGHT = WORLD_HEIGHT * 4;

export const WORLD_DETAILS_WIDTH = 2 * ((1024 - 250) / 1024);
export const WORLD_DETAILS_HEIGHT = WORLD_DETAILS_WIDTH / DETAILS_ASPECT_RATIO;

export default {
  WIDTH,
  HEIGHT,
  ASPECT_RATIO,
  OPEN_WIDTH,
  OPEN_HEIGHT,
  DETAILS_ASPECT_RATIO,
  DETAILS_WIDTH,
  DETAILS_HEIGHT,
  WORLD_WIDTH,
  WORLD_HEIGHT,
  WORLD_DEPTH,
  WORLD_OPEN_WIDTH,
  WORLD_OPEN_HEIGHT,
  WORLD_DETAILS_WIDTH,
  WORLD_DETAILS_HEIGHT,
};
