const WIDTH = 1920;
const HEIGHT = Math.round(WIDTH * 3 / 4);
const ASPECT_RATIO = WIDTH / HEIGHT;
const WORLD_WIDTH = 2;
const WORLD_HEIGHT = WORLD_WIDTH / ASPECT_RATIO;
const WORLD_DEPTH = WORLD_WIDTH / 50;

const ITEM_MENU_SIZE = 760;
const ITEM_MENU_INNER_SIZE = 640;
const ITEM_MENU_BORDER_SIZE = ITEM_MENU_SIZE * 0.05;
const ITEM_MENU_WORLD_SIZE = 0.4;

const DEFAULT_USER_HEIGHT = 1.6;

module.exports = {
  WIDTH,
  HEIGHT,
  ASPECT_RATIO,
  WORLD_WIDTH,
  WORLD_HEIGHT,
  WORLD_DEPTH,

  ITEM_MENU_SIZE,
  ITEM_MENU_INNER_SIZE,
  ITEM_MENU_BORDER_SIZE,
  ITEM_MENU_WORLD_SIZE,

  DEFAULT_USER_HEIGHT,
};
