export const HEIGHT = 128;
export const ASPECT_RATIO = 1.5;
export const WIDTH = HEIGHT * ASPECT_RATIO;
export const WORLD_WIDTH = 2;
export const WORLD_HEIGHT = WORLD_WIDTH / ASPECT_RATIO;
export const WORLD_DEPTH = 0.01;
export const NUM_CELLS = HEIGHT;

export const FOREGROUND_WIDTH = 1024;
export const FOREGROUND_ASPECT_RATIO = 1.5;
export const FOREGROUND_HEIGHT = FOREGROUND_WIDTH / FOREGROUND_ASPECT_RATIO;
export const FOREGROUND_WORLD_WIDTH = 2;
export const FOREGROUND_WORLD_HEIGHT = FOREGROUND_WORLD_WIDTH / FOREGROUND_ASPECT_RATIO;
export const FOREGROUND_WORLD_DEPTH = 0.01;
export const FOREGROUND_SIZE = FOREGROUND_HEIGHT;
