export const WIDTH = 1024;
export const HEIGHT = Math.round(WIDTH / 1.5);
export const ASPECT_RATIO = WIDTH / HEIGHT;
export const WORLD_WIDTH = 2;
export const WORLD_HEIGHT = WORLD_WIDTH / ASPECT_RATIO;
export const WORLD_DEPTH = 0.01;

export const TAGS_WIDTH = 400;
export const TAGS_HEIGHT = 150;
export const TAGS_ASPECT_RATIO = TAGS_WIDTH / TAGS_HEIGHT;
export const TAGS_WORLD_WIDTH = 0.2;
export const TAGS_WORLD_HEIGHT = TAGS_WORLD_WIDTH / TAGS_ASPECT_RATIO;
export const TAGS_WORLD_DEPTH = 0.01;

export default {
  WIDTH,
  HEIGHT,
  ASPECT_RATIO,
  WORLD_WIDTH,
  WORLD_HEIGHT,
  WORLD_DEPTH,
  TAGS_WIDTH,
  TAGS_HEIGHT,
  TAGS_ASPECT_RATIO,
  TAGS_WORLD_WIDTH,
  TAGS_WORLD_HEIGHT,
  TAGS_WORLD_DEPTH,
};
