const NUM_CELLS = 64;
const OVERSCAN = 1;
const NUM_CELLS_OVERSCAN = NUM_CELLS + OVERSCAN;

const NUM_CELLS_HEIGHT = 60;
const HEIGHT_OFFSET = -10;

const DEFAULT_SEED = 'a';

module.exports = {
  NUM_CELLS,
  OVERSCAN,
  NUM_CELLS_OVERSCAN,

  NUM_CELLS_HEIGHT,
  HEIGHT_OFFSET,

  DEFAULT_SEED,
};
