const NUM_CELLS = 32;
const OVERSCAN = 1;
const NUM_CELLS_OVERSCAN = NUM_CELLS + OVERSCAN;

const DEFAULT_SEED = 'a';

module.exports = {
  NUM_CELLS,
  OVERSCAN,
  NUM_CELLS_OVERSCAN,
  DEFAULT_SEED,
};
