export const WIDTH = 1024;
export const HEIGHT = WIDTH / 1.5;
export const ASPECT_RATIO = WIDTH / HEIGHT;
export const WORLD_WIDTH = 2;
export const WORLD_HEIGHT = WORLD_WIDTH / ASPECT_RATIO;
export const WORLD_DEPTH = WORLD_WIDTH / 50;

export const STATS_WIDTH = 500;
export const STATS_ASPECT_RATIO = 80 / 48;
export const STATS_HEIGHT = STATS_WIDTH / STATS_ASPECT_RATIO;
export const STATS_WORLD_WIDTH = 0.2;
export const STATS_WORLD_HEIGHT = STATS_WORLD_WIDTH / STATS_ASPECT_RATIO;
export const STATS_WORLD_DEPTH = STATS_WORLD_WIDTH / 50;

export const STATS_REFRESH_RATE = 1000;
