const WIDTH = 320;
const HEIGHT = 240;
const ASPECT_RATIO = WIDTH / HEIGHT;
const WORLD_WIDTH = 2;
const WORLD_HEIGHT = WORLD_WIDTH / ASPECT_RATIO;
const WORLD_DEPTH = WORLD_WIDTH / 50;

const PORT = 9999;

module.exports = {
  WIDTH,
  HEIGHT,
  ASPECT_RATIO,
  WORLD_WIDTH,
  WORLD_HEIGHT,
  WORLD_DEPTH,

  PORT,
};
