export const KEYBOARD_WIDTH = 2048;
export const KEYBOARD_ASPECT_RATIO = 1000 / 350;
export const KEYBOARD_HEIGHT = KEYBOARD_WIDTH / KEYBOARD_ASPECT_RATIO;
export const KEYBOARD_WORLD_WIDTH = 1;
export const KEYBOARD_WORLD_HEIGHT = KEYBOARD_WORLD_WIDTH / KEYBOARD_ASPECT_RATIO;
export const KEYBOARD_WORLD_DEPTH = KEYBOARD_WORLD_WIDTH / 50;

export const KEYBOARD_HEADER_WIDTH = 1200;
export const KEYBOARD_HEADER_HEIGHT = 50;
export const KEYBOARD_HEADER_ASPECT_RATIO = KEYBOARD_HEADER_WIDTH / KEYBOARD_HEADER_HEIGHT;
export const KEYBOARD_HEADER_WORLD_WIDTH = 1;
export const KEYBOARD_HEADER_WORLD_HEIGHT = KEYBOARD_HEADER_WORLD_WIDTH / KEYBOARD_HEADER_ASPECT_RATIO;
export const KEYBOARD_HEADER_WORLD_DEPTH = KEYBOARD_HEADER_WORLD_WIDTH / 50;

export const DEFAULT_USER_HEIGHT = 1.6;

export default {};
