export const WIDTH = 1024;
export const HEIGHT = Math.round(WIDTH / 1.5);
export const ASPECT_RATIO = WIDTH / HEIGHT;
export const WORLD_WIDTH = 2;
export const WORLD_HEIGHT = WORLD_WIDTH / ASPECT_RATIO;
export const WORLD_DEPTH = WORLD_WIDTH / 50;

export const TAGS_WIDTH = 400;
export const TAGS_HEIGHT = 150;
export const TAGS_ASPECT_RATIO = TAGS_WIDTH / TAGS_HEIGHT;
export const TAGS_WORLD_WIDTH = 0.2;
export const TAGS_WORLD_HEIGHT = TAGS_WORLD_WIDTH / TAGS_ASPECT_RATIO;
export const TAGS_WORLD_DEPTH = 0.02;

export const WALKTHROUGH_WIDTH = 150;
export const WALKTHROUGH_HEIGHT = 200;
export const WALKTHROUGH_ASPECT_RATIO = WALKTHROUGH_WIDTH / WALKTHROUGH_HEIGHT;
export const WALKTHROUGH_WORLD_WIDTH = 0.1;
export const WALKTHROUGH_WORLD_HEIGHT = WALKTHROUGH_WORLD_WIDTH / WALKTHROUGH_ASPECT_RATIO;
export const WALKTHROUGH_WORLD_DEPTH = 0.02;

export const SERVER_WIDTH = 1024;
export const SERVER_HEIGHT = Math.round(SERVER_WIDTH / 2.5);
export const SERVER_ASPECT_RATIO = SERVER_WIDTH / SERVER_HEIGHT;
export const SERVER_WORLD_WIDTH = 0.7;
export const SERVER_WORLD_HEIGHT = SERVER_WORLD_WIDTH / SERVER_ASPECT_RATIO;
export const SERVER_WORLD_DEPTH = SERVER_WORLD_WIDTH / 50;

export const SPHERE_RADIUS = 0.2;

export const DEFAULT_USER_HEIGHT = 1.6;

export default {
  WIDTH,
  HEIGHT,
  ASPECT_RATIO,
  WORLD_WIDTH,
  WORLD_HEIGHT,
  WORLD_DEPTH,

  WALKTHROUGH_WIDTH,
  WALKTHROUGH_HEIGHT,
  WALKTHROUGH_ASPECT_RATIO,
  WALKTHROUGH_WORLD_WIDTH,
  WALKTHROUGH_WORLD_HEIGHT,
  WALKTHROUGH_WORLD_DEPTH,

  TAGS_WIDTH,
  TAGS_HEIGHT,
  TAGS_ASPECT_RATIO,
  TAGS_WORLD_WIDTH,
  TAGS_WORLD_HEIGHT,
  TAGS_WORLD_DEPTH,

  SERVER_WIDTH,
  SERVER_HEIGHT,
  SERVER_ASPECT_RATIO,
  SERVER_WORLD_WIDTH,
  SERVER_WORLD_HEIGHT,
  SERVER_WORLD_DEPTH,

  SPHERE_RADIUS,

  DEFAULT_USER_HEIGHT,
};
