const WIDTH = 1920;
const HEIGHT = Math.round(WIDTH * 0.5);
const ASPECT_RATIO = WIDTH / HEIGHT;
const WORLD_WIDTH = 2;
const WORLD_HEIGHT = WORLD_WIDTH / ASPECT_RATIO;
const WORLD_DEPTH = WORLD_WIDTH / 50;

const DEFAULT_USER_HEIGHT = 1.6;

module.exports = {
  WIDTH,
  HEIGHT,
  ASPECT_RATIO,
  WORLD_WIDTH,
  WORLD_HEIGHT,
  WORLD_DEPTH,

  DEFAULT_USER_HEIGHT,
};
